extends Node

signal nuevo_beat()
signal tierra()
signal agua()
signal fuego()
signal planta()
signal fallo()
signal win()
signal lives_changed()
signal finish_dialoge()
signal tiki_mask()
signal japo_mask()
signal tragicomedia_mask()
signal plaga_mask()
signal increchendo(num:float)
signal mask_off(tipo:String)
signal kill(num:int)
